import { Toaster } from "@/components/ui/sonner";
import { auth } from "@/lib/session";
import { uploadRouter } from "@/lib/upload/uploadthing-server";
import { SessionProvider } from "@/provider/session-provider";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { extractRouterConfig } from "uploadthing/server";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "PDF Axiom",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextSSRPlugin routerConfig={extractRouterConfig(uploadRouter)} />

        <SessionProvider session={session}>{children}</SessionProvider>

        <Toaster richColors />
      </body>
    </html>
  );
}
